# Generated by Django 6.0.6 on 2026-06-28 21:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choreography',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('thumbnail_url', models.URLField(max_length=500)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest_teachers', models.ManyToManyField(blank=True, related_name='guest_choreographies', to=settings.AUTH_USER_MODEL)),
                ('main_teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_choreographies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DanceStyle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChoreographyStat',
            fields=[
                ('choreography', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stats', serialize=False, to='choreography.choreography')),
                ('actual_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_views', models.IntegerField(default=0)),
                ('total_sales_count', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='choreography',
            name='dance_style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='choreographies', to='choreography.dancestyle'),
        ),
        migrations.CreateModel(
            name='PriceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('choreography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choreography.choreography')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RatingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_rating', models.IntegerField(blank=True, null=True)),
                ('new_rating', models.IntegerField()),
                ('action_type', models.CharField(max_length=50)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('choreography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choreography.choreography')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choreography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='choreography.choreography')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choreography_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoClip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('video_url', models.URLField(max_length=500)),
                ('sequence_order', models.IntegerField()),
                ('duration_seconds', models.IntegerField()),
                ('choreography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='choreography.choreography')),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='VideoPlaybackLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video_clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choreography.videoclip')),
            ],
        ),
    ]
